
services:
  db:
    container_name: appDB
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appDB
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: .
    depends_on:
      - db
    container_name: go_app
    volumes:
      - ./config/config.yaml:/root/config.yaml
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  data:

networks:
  app_network:
    driver: bridge

