definitions:
  bookingModule.BookingModel:
    properties:
      delta:
        description: Длительность бронирования (например, в минутах)
        type: integer
      endTime:
        description: Время окончания бронирования
        type: string
      id:
        description: Уникальный идентификатор бронирования
        type: string
      startTime:
        description: Время начала бронирования
        type: string
      username:
        description: Имя пользователя, сделавшего бронирование
        type: string
    type: object
  handlers.Answer:
    properties:
      data:
        description: Данные ответа
      status:
        description: Код состояния HTTP
        type: integer
    type: object
  userModule.UserModel:
    properties:
      ID:
        description: Уникальный идентификатор пользователя
        type: string
      createdAt:
        description: Время создания записи пользователя
        type: string
      password:
        description: Пароль пользователя (в идеале, храните в хешированном виде)
        type: string
      updatedAt:
        description: Время последнего обновления записи пользователя
        type: string
      username:
        description: Имя пользователя (логин)
        type: string
    type: object
info:
  contact: {}
paths:
  /booking:
    post:
      consumes:
      - application/json
      description: Create a new booking with the provided details
      parameters:
      - description: Booking data
        in: body
        name: booking
        required: true
        schema:
          $ref: '#/definitions/bookingModule.BookingModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.Answer'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/handlers.Answer'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.Answer'
      summary: Create a booking
      tags:
      - booking
  /booking/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a booking by its ID
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No content
          schema:
            $ref: '#/definitions/handlers.Answer'
        "404":
          description: Booking not found
          schema:
            $ref: '#/definitions/handlers.Answer'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.Answer'
      summary: Delete a booking
      tags:
      - booking
    get:
      consumes:
      - application/json
      description: Get a booking by its ID
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Booking details
          schema:
            $ref: '#/definitions/handlers.Answer'
        "404":
          description: Booking not found
          schema:
            $ref: '#/definitions/handlers.Answer'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.Answer'
      summary: Find a booking
      tags:
      - booking
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user with the provided information
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/userModule.UserModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.Answer'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/handlers.Answer'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.Answer'
      summary: Create a user
      tags:
      - user
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user by their ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No content
          schema:
            $ref: '#/definitions/handlers.Answer'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/handlers.Answer'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.Answer'
      summary: Delete a user
      tags:
      - user
swagger: "2.0"
